Repository oracle/terraform-provider-oci, pull requests merged in 2019-01, with the labels that each got.

#686 Revert "Add a customdiff into Instance resource to track nested metad…
  CHANGELOG.md
  oci/core_instance_resource.go
  oci/core_instance_resource_test.go
  oci/version.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/compose.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/computed.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/condition.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/doc.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/force_new.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/validate.go
  vendor/vendor.json
Labels: dependencies, size/XL

#691 hotfix for example fix in lb_full
  docs/examples/load_balancer/lb_full/lb_full.tf
Labels: size/XS

#692 Typo
  website/docs/r/core_app_catalog_listing_resource_version_agreement.html.markdown
Labels: documentation, size/XS

#694 Move to Go v1.11.4
  .travis.yml
  CHANGELOG.md
  README.md
  docs/examples/load_balancer/lb_full/lb_full.tf
  docs/examples/object_storage/object.tf
  main.go
  oci/core_instance_pool_test.go
  oci/core_instance_resource.go
  oci/core_route_table_attachment_test.go
  oci/core_virtual_circuit_test.go
  oci/filters_integration_test.go
  oci/helpers_objectstorage.go
  oci/identity_compartment_resource.go
  oci/identity_compartment_test.go
  oci/identity_policies_data_source_test.go
  oci/identity_policy_scenario_test.go
  oci/identity_policy_test.go
  oci/identity_user_capabilities_management_resource_test.go
  oci/load_balancer_backend_set_resource_test.go
  oci/load_balancer_backend_set_test.go
  oci/load_balancer_backend_sets_data_source_test.go
  oci/load_balancer_certificate_resource_test.go
  oci/load_balancer_certificate_test.go
  oci/load_balancer_certificates_data_source_test.go
  oci/load_balancer_listener_resource_test.go
  oci/object_storage_object_data_source.go
  oci/object_storage_object_lifecycle_policy_test.go
  oci/object_storage_object_test.go
  oci/provider.go
  website/docs/d/object_storage_object.html.markdown
  website/docs/r/identity_compartment.html.markdown
  website/oci.erb
Labels: documentation, size/XL

#695 Release
  CHANGELOG.md
  oci/core_instance_resource.go
  oci/core_instance_resource_test.go
  oci/provider.go
  oci/version.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/compose.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/computed.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/condition.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/doc.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/force_new.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/validate.go
  vendor/github.com/hashicorp/terraform/helper/schema/field_reader_config.go
  vendor/github.com/hashicorp/terraform/helper/schema/field_reader_diff.go
  vendor/vendor.json
Labels: dependencies, size/XL

#699 Update tags.tf
  docs/examples/identity/tags.tf
Labels: size/XS

#701 Update go version in wercker builds and fix samples formatting
  docs/examples/identity/tags.tf
  wercker.yml
Labels: size/XS

#702 Release 3.14.0
  CHANGELOG.md
  oci/audit_configuration_resource.go
  oci/database_db_system_resource.go
  oci/version.go
  vendor/github.com/oracle/oci-go-sdk/CHANGELOG.md
  vendor/github.com/oracle/oci-go-sdk/common/auth/instance_principal_key_provider.go
  vendor/github.com/oracle/oci-go-sdk/common/client.go
  vendor/github.com/oracle/oci-go-sdk/common/common.go
  vendor/github.com/oracle/oci-go-sdk/common/http.go
  vendor/github.com/oracle/oci-go-sdk/common/log.go
  vendor/github.com/oracle/oci-go-sdk/common/version.go
  vendor/github.com/oracle/oci-go-sdk/database/create_database_from_backup_details.go
  vendor/github.com/oracle/oci-go-sdk/oci.go
  vendor/vendor.json
  website/docs/d/database_autonomous_data_warehouse.html.markdown
  website/docs/d/database_autonomous_data_warehouses.html.markdown
  website/docs/d/database_autonomous_database.html.markdown
  website/docs/d/database_autonomous_databases.html.markdown
  website/docs/r/database_autonomous_data_warehouse.html.markdown
  website/docs/r/database_autonomous_database.html.markdown
  website/docs/r/database_db_system.html.markdown
Labels: dependencies, documentation, size/L
