Repository oracle/terraform-provider-oci, pull requests merged in 2020-08, with the labels that each got.

#1139 Database Data source document updated
  website/docs/d/database_databases.html.markdown
Labels: documentation, size/XS

#1145 Candidate for release_v3.89.0
  oci/core_instance_resource.go
Labels: size/S

#1146 Releasing version 3.89.0
  oci/core_instance_resource.go
Labels: size/S

#1156 Candidate for release_v3.90.1
  CHANGELOG.md
  examples/database/atp-d/exadata.tf
  examples/database/atp-d/main.tf
  infrastructure/resource_discovery/script/apply_job.sh
  infrastructure/resource_discovery/script/destroy_job.sh
  infrastructure/resource_discovery/script/run_test.sh
  infrastructure/resource_discovery/script/update_stack.sh
  infrastructure/resource_discovery/transient/atp_d.tf
  oci/core_instance_resource_test.go
  oci/database_autonomous_container_database_resource_test.go
  oci/database_autonomous_container_database_test.go
  oci/database_autonomous_exadata_infrastructure_test.go
  oci/database_backups_data_source.go
  oci/database_exadata_infrastructure_resource_test.go
  oci/database_exadata_infrastructure_test.go
  oci/export_compartment_test.go
  oci/export_definitions.go
  oci/export_graphs.go
  oci/oci_dependency_graph.go
  oci/test_helpers.go
  oci/version.go
  website/docs/guides/resource_discovery.html.markdown
Labels: documentation, size/XL

#1157 Releasing version 3.90.1
  CHANGELOG.md
  examples/database/atp-d/exadata.tf
  examples/database/atp-d/main.tf
  infrastructure/resource_discovery/script/apply_job.sh
  infrastructure/resource_discovery/script/destroy_job.sh
  infrastructure/resource_discovery/script/run_test.sh
  infrastructure/resource_discovery/script/update_stack.sh
  infrastructure/resource_discovery/transient/atp_d.tf
  oci/core_instance_resource_test.go
  oci/database_autonomous_container_database_resource_test.go
  oci/database_autonomous_container_database_test.go
  oci/database_autonomous_exadata_infrastructure_test.go
  oci/database_backups_data_source.go
  oci/database_exadata_infrastructure_resource_test.go
  oci/database_exadata_infrastructure_test.go
  oci/export_compartment_test.go
  oci/export_definitions.go
  oci/export_graphs.go
  oci/oci_dependency_graph.go
  oci/test_helpers.go
  oci/version.go
  website/docs/guides/resource_discovery.html.markdown
Labels: documentation, size/XL
