Repository oracle/terraform-provider-oci, pull requests merged in 2020-07, with the labels that each got.

#1107 Fix private ip resource doc to remove unwanted characters
  website/docs/r/core_private_ip.html.markdown
Labels: documentation, size/XS

#1109 Reverted the default value to true for assign_public_ip in oci_core_instance resource
  CHANGELOG.md
  oci/core_instance_resource.go
  oci/core_instance_test.go
  oci/core_vnic_attachment_test.go
  oci/version.go
Labels: size/XS

#1120 Candidate for release_v3.86.0
  CHANGELOG.md
  examples/oce/main.tf
  examples/storage/fss/variables.tf
  go.mod
  go.sum
  oci/audit_configuration_test.go
  oci/budget_alert_rule_test.go
  oci/budget_budget_test.go
  oci/core_dhcp_options_resource_test.go
  oci/core_volume_attachment_resource.go
  oci/core_volume_attachment_test.go
  oci/datacatalog_connection_test.go
  oci/email_suppression_test.go
  oci/export_compartment.go
  oci/export_compartment_test.go
  oci/export_resource_helpers.go
  oci/helpers.go
  oci/kms_key_test.go
  oci/limits_quota_test.go
  oci/log.go
  oci/oce_oce_instance_data_source.go
  oci/oce_oce_instance_resource.go
  oci/oce_oce_instance_test.go
  oci/oce_oce_instances_data_source.go
  oci/osmanagement_managed_instance_management_test.go
  oci/osmanagement_managed_instance_test.go
  oci/version.go
  vendor/github.com/oracle/oci-go-sdk/common/version.go
  vendor/github.com/oracle/oci-go-sdk/oce/create_oce_instance_details.go
  vendor/github.com/oracle/oci-go-sdk/oce/identity_stripe_details.go
  vendor/github.com/oracle/oci-go-sdk/oce/license_type.go
  vendor/github.com/oracle/oci-go-sdk/oce/oce_instance.go
  vendor/github.com/oracle/oci-go-sdk/oce/oce_instance_summary.go
  vendor/github.com/oracle/oci-go-sdk/oce/update_oce_instance_details.go
  vendor/modules.txt
  website/docs/d/oce_oce_instance.html.markdown
  website/docs/d/oce_oce_instances.html.markdown
  website/docs/r/oce_oce_instance.html.markdown
Labels: dependencies, size/XL

#1121 Releasing version 3.86.0
  CHANGELOG.md
  examples/oce/main.tf
  examples/storage/fss/variables.tf
  go.mod
  go.sum
  oci/audit_configuration_test.go
  oci/budget_alert_rule_test.go
  oci/budget_budget_test.go
  oci/core_dhcp_options_resource_test.go
  oci/core_volume_attachment_resource.go
  oci/core_volume_attachment_test.go
  oci/datacatalog_connection_test.go
  oci/email_suppression_test.go
  oci/export_compartment.go
  oci/export_compartment_test.go
  oci/export_resource_helpers.go
  oci/helpers.go
  oci/kms_key_test.go
  oci/limits_quota_test.go
  oci/log.go
  oci/oce_oce_instance_data_source.go
  oci/oce_oce_instance_resource.go
  oci/oce_oce_instance_test.go
  oci/oce_oce_instances_data_source.go
  oci/osmanagement_managed_instance_management_test.go
  oci/osmanagement_managed_instance_test.go
  oci/version.go
  vendor/github.com/oracle/oci-go-sdk/common/version.go
  vendor/github.com/oracle/oci-go-sdk/oce/create_oce_instance_details.go
  vendor/github.com/oracle/oci-go-sdk/oce/identity_stripe_details.go
  vendor/github.com/oracle/oci-go-sdk/oce/license_type.go
  vendor/github.com/oracle/oci-go-sdk/oce/oce_instance.go
  vendor/github.com/oracle/oci-go-sdk/oce/oce_instance_summary.go
  vendor/github.com/oracle/oci-go-sdk/oce/update_oce_instance_details.go
  vendor/modules.txt
  website/docs/d/oce_oce_instance.html.markdown
  website/docs/d/oce_oce_instances.html.markdown
  website/docs/r/oce_oce_instance.html.markdown
Labels: dependencies, size/XL
