Repository oracle/terraform-provider-oci, pull requests merged in 2020-09, with the labels that each got.

#1159 make load_balancer_ssl_configuration_protocols computed
  examples/load_balancer/lb_full/lb_full.tf
  oci/load_balancer_backend_set_resource.go
  oci/load_balancer_backend_set_test.go
  oci/load_balancer_listener_resource.go
  oci/load_balancer_listener_test.go
Labels: size/XS

#1162 fix example and terraform import for loadbalancer
  examples/load_balancer/lb_full/lb_full.tf
  oci/load_balancer_backend_set_resource.go
  oci/load_balancer_backend_set_test.go
  oci/load_balancer_listener_resource.go
Labels: size/S

#1188 revert break changes
  oci/core_instance_resource.go
  oci/core_instance_resource_test.go
Labels: size/M
